# moonlight-launcher configuration file
# Put any edits below.  Lines beginning with '#' are comments.

# Default host IP for streaming
# — default: 192.168.0.2
HOST_IP="192.168.0.2"

# Default Moonlight app to launch
# — default: Desktop
APP_NAME="Desktop"

# Default resolution flag.
# — options: "-720", "-1080", "-4k", "custom"
# — default: "-1080"
RESOLUTION_FLAG="-1080"

# When RESOLUTION_FLAG="custom", these are used:
# — default width: 2560
CUSTOM_WIDTH="2560"
# — default height: 1440
CUSTOM_HEIGHT="1440"

# Default frames-per-second
# — default: 60
FPS="60"

# Default bitrate (in kilobits per second)
# — default: 40000
BITRATE="40000"

# Use local audio playback?
# — options: "yes" or "no"
# — default: no
LOCAL_AUDIO="no"
